// frontend/src/components/BabyShopping.jsx
import { useEffect, useMemo, useState } from 'react'
import api from '../api'

const categories = ['Clothes', 'Toys', 'Furniture', 'Essentials']

const currencyFormatter = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR',
})

export default function BabyShopping() {
  const [expenses, setExpenses] = useState([])
  const [form, setForm] = useState({
    description: '',
    amount: '',
    date: new Date().toISOString().split('T')[0],
    category: categories[0],
    bill: '',
  })
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState({
    total: 0,
    highestMonth: { month: null, amount: 0 },
    average: 0,
  })
  const [error, setError] = useState(null)
  const [success, setSuccess] = useState(null)
  const [editingId, setEditingId] = useState(null)

  const fetchExpenses = async () => {
    try {
      const response = await api.get('/api/baby-shopping')
      setExpenses(response.data || [])
    } catch (err) {
      console.error('Failed to load baby shopping expenses', err)
      setError('Unable to load baby shopping expenses')
    }
  }

  const fetchSummary = async () => {
    try {
      const response = await api.get('/api/baby-shopping/summary')
      setSummary(response.data || { total: 0, highestMonth: { month: null, amount: 0 }, average: 0 })
    } catch (err) {
      console.error('Failed to load summary', err)
    }
  }

  useEffect(() => {
    fetchExpenses()
    fetchSummary()
  }, [])

  const handleChange = (field, value) => {
    setForm((prev) => ({ ...prev, [field]: value }))
  }

  const resetForm = () => {
    setForm({
      description: '',
      amount: '',
      date: new Date().toISOString().split('T')[0],
      category: categories[0],
      bill: '',
    })
    setEditingId(null)
    setError(null)
    setSuccess(null)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError(null)
    setSuccess(null)

    if (!form.description || !form.amount || !form.date) {
      setError('Please complete all required fields.')
      return
    }

    setLoading(true)
    try {
      const payload = {
        description: form.description,
        amount: Number(form.amount),
        date: form.date,
        category: form.category,
        bill: form.bill,
      }

      if (editingId) {
        await api.put(`/api/baby-shopping/${editingId}`, payload)
        setSuccess('Expense updated successfully.')
      } else {
        await api.post('/api/baby-shopping', payload)
        setSuccess('Expense added successfully.')
      }

      resetForm()
      await fetchExpenses()
      await fetchSummary()
    } catch (err) {
      console.error('Save failed', err)
      setError('Failed to save the expense.')
    } finally {
      setLoading(false)
    }
  }

  const handleEdit = (expense) => {
    setEditingId(expense.id)
    setForm({
      description: expense.description || '',
      amount: expense.amount?.toString() || '',
      date: expense.date || new Date().toISOString().split('T')[0],
      category: expense.category || categories[0],
      bill: expense.bill || '',
    })
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const handleDelete = async (id) => {
    const confirmed = window.confirm('Delete this baby shopping expense?')
    if (!confirmed) return

    try {
      await api.delete(`/api/baby-shopping/${id}`)
      await fetchExpenses()
      await fetchSummary()
    } catch (err) {
      console.error('Delete failed', err)
      setError('Failed to delete expense.')
    }
  }

  const totalExpenses = useMemo(() => summary.total ?? 0, [summary])

  return (
    <div className="space-y-8">
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="rounded-3xl border border-teal-100 bg-teal-50 p-6 shadow-lg dark:border-teal-800 dark:bg-teal-950/20 transition duration-500">
          <p className="text-sm uppercase tracking-[0.24em] text-teal-700 dark:text-teal-300">Total Baby Shopping</p>
          <h2 className="mt-4 text-4xl font-bold text-slate-900 dark:text-white">{currencyFormatter.format(totalExpenses)}</h2>
        </div>
        <div className="rounded-3xl border border-purple-100 bg-purple-50 p-6 shadow-lg dark:border-purple-800 dark:bg-purple-950/20 transition duration-500">
          <p className="text-sm uppercase tracking-[0.24em] text-purple-700 dark:text-purple-300">Highest Month</p>
          <h2 className="mt-4 text-3xl font-bold text-slate-900 dark:text-white">Month {summary.highestMonth?.month || '—'}</h2>
          <p className="mt-2 text-slate-600 dark:text-slate-300">{currencyFormatter.format(summary.highestMonth?.amount ?? 0)}</p>
        </div>
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-lg dark:border-slate-800 dark:bg-slate-900 transition duration-500">
          <p className="text-sm uppercase tracking-[0.24em] text-slate-500 dark:text-slate-400">Average Monthly</p>
          <h2 className="mt-4 text-3xl font-bold text-slate-900 dark:text-white">{currencyFormatter.format(summary.average ?? 0)}</h2>
        </div>
      </div>

      <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900 transition duration-500">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Add Baby Shopping Expense</h2>
            <p className="mt-2 text-slate-600 dark:text-slate-300">Capture clothes, toys, furniture, and essentials purchases.</p>
          </div>
          <button
            type="button"
            onClick={resetForm}
            className="rounded-full border border-slate-300 bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-900 transition hover:border-teal-400 hover:bg-teal-50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
          >
            Reset form
          </button>
        </div>

        {error && (
          <div className="mt-6 rounded-2xl bg-rose-50 p-4 text-rose-700 dark:bg-rose-950/40 dark:text-rose-200">
            {error}
          </div>
        )}
        {success && (
          <div className="mt-6 rounded-2xl bg-emerald-50 p-4 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-200">
            {success}
          </div>
        )}

        <form onSubmit={handleSubmit} className="mt-8 grid gap-6 lg:grid-cols-2">
          <label className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            <span>Description</span>
            <input
              type="text"
              value={form.description}
              onChange={(e) => handleChange('description', e.target.value)}
              className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-teal-400 focus:ring-2 focus:ring-teal-200/50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
              placeholder="Baby blanket, feeding set, etc."
              required
            />
          </label>

          <label className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            <span>Amount</span>
            <input
              type="number"
              value={form.amount}
              onChange={(e) => handleChange('amount', e.target.value)}
              className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-teal-400 focus:ring-2 focus:ring-teal-200/50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
              min="0"
              step="0.01"
              required
            />
          </label>

          <label className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            <span>Date</span>
            <input
              type="date"
              value={form.date}
              onChange={(e) => handleChange('date', e.target.value)}
              className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-teal-400 focus:ring-2 focus:ring-teal-200/50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
              required
            />
          </label>

          <label className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            <span>Category</span>
            <select
              value={form.category}
              onChange={(e) => handleChange('category', e.target.value)}
              className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-teal-400 focus:ring-2 focus:ring-teal-200/50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
            >
              {categories.map((category) => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
          </label>

          <label className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
            <span>Bill Upload</span>
            <input
              type="text"
              value={form.bill}
              onChange={(e) => handleChange('bill', e.target.value)}
              className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-teal-400 focus:ring-2 focus:ring-teal-200/50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
              placeholder="Bill file name or URL"
            />
          </label>

          <div className="lg:col-span-2 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <button
              type="submit"
              disabled={loading}
              className="rounded-2xl bg-teal-600 px-6 py-3 text-sm font-semibold text-white transition hover:bg-teal-700 disabled:opacity-60"
            >
              {loading ? 'Saving...' : editingId ? 'Update Expense' : 'Add Expense'}
            </button>
            <button
              type="button"
              onClick={resetForm}
              className="rounded-2xl border border-slate-300 bg-slate-100 px-6 py-3 text-sm font-semibold text-slate-900 transition hover:border-teal-400 hover:bg-teal-50 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
            >
              Reset
            </button>
          </div>
        </form>
      </div>

      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xl dark:border-slate-800 dark:bg-slate-900 transition duration-500">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-700">
            <thead className="bg-slate-50 dark:bg-slate-950">
              <tr>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Description</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Amount</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Date</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Category</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Bill</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-slate-700 dark:text-slate-300">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-700">
              {expenses.map((expense) => (
                <tr key={expense.id} className="hover:bg-slate-50 dark:hover:bg-slate-950 transition duration-150">
                  <td className="px-4 py-4 text-sm text-slate-900 dark:text-slate-100">{expense.description}</td>
                  <td className="px-4 py-4 text-sm font-semibold text-slate-900 dark:text-teal-300">{currencyFormatter.format(expense.amount || 0)}</td>
                  <td className="px-4 py-4 text-sm text-slate-600 dark:text-slate-300">{new Date(expense.date).toLocaleDateString()}</td>
                  <td className="px-4 py-4 text-sm text-slate-900 dark:text-slate-100">{expense.category}</td>
                  <td className="px-4 py-4 text-sm text-slate-600 dark:text-slate-300">{expense.bill || '—'}</td>
                  <td className="px-4 py-4 text-sm text-slate-900 dark:text-slate-100 space-x-2">
                    <button
                      type="button"
                      onClick={() => handleEdit(expense)}
                      className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-800 transition hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-100 dark:hover:bg-slate-700"
                    >
                      Edit
                    </button>
                    <button
                      type="button"
                      onClick={() => handleDelete(expense.id)}
                      className="rounded-full bg-rose-100 px-3 py-1 text-sm font-semibold text-rose-700 transition hover:bg-rose-200 dark:bg-rose-950 dark:text-rose-200 dark:hover:bg-rose-900"
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/BabyShopping.vue
<template>
  <div class="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-10">
    <div class="mx-auto max-w-6xl">
      <h1 class="text-3xl font-semibold text-slate-900 mb-6">Baby Shopping</h1>

      <div class="grid gap-6 lg:grid-cols-[1.2fr_1fr]">
        <section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <h2 class="text-xl font-semibold text-slate-800 mb-4">Add Shopping Item</h2>
          <form @submit.prevent="submitShopping" class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2" for="itemName">Item Name</label>
              <input
                id="itemName"
                v-model="form.name"
                type="text"
                placeholder="Enter item name"
                class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-sky-400 focus:ring-2 focus:ring-sky-100"
                required
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2" for="category">Category</label>
              <select
                id="category"
                v-model="form.category"
                class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-sky-400 focus:ring-2 focus:ring-sky-100"
                required
              >
                <option value="" disabled>Select category</option>
                <option>Clothes</option>
                <option>Toys</option>
                <option>Essentials</option>
              </select>
            </div>

            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2" for="price">Price</label>
              <input
                id="price"
                v-model.number="form.price"
                type="number"
                min="0"
                step="0.01"
                placeholder="0.00"
                class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-sky-400 focus:ring-2 focus:ring-sky-100"
                required
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-slate-700 mb-2" for="purchaseDate">Purchase Date</label>
              <input
                id="purchaseDate"
                v-model="form.date"
                type="date"
                class="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-900 outline-none transition focus:border-sky-400 focus:ring-2 focus:ring-sky-100"
                required
              />
            </div>

            <button
              type="submit"
              class="inline-flex w-full items-center justify-center rounded-2xl bg-sky-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-sky-300"
            >
              Add Item
            </button>
          </form>
        </section>

        <section class="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div class="flex items-center justify-between mb-4">
            <h2 class="text-xl font-semibold text-slate-800">Saved Items</h2>
            <span class="text-sm text-slate-500">{{ shoppingItems.length }} items</span>
          </div>

          <div class="space-y-4">
            <article
              v-for="item in shoppingItems"
              :key="item.id || item.date + item.name"
              class="rounded-3xl border border-slate-200 bg-slate-50 p-4 shadow-sm"
            >
              <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <h3 class="text-lg font-semibold text-slate-900">{{ item.name }}</h3>
                  <p class="text-sm text-slate-600">{{ item.category }}</p>
                </div>
                <div class="flex flex-col items-start gap-1 text-right sm:items-end">
                  <span class="text-lg font-semibold text-slate-900">${{ formatAmount(item.price) }}</span>
                  <span class="text-sm text-slate-500">{{ formatDate(item.date) }}</span>
                </div>
              </div>
            </article>
          </div>

          <div class="mt-6 rounded-3xl bg-slate-900 p-5 text-white shadow-lg">
            <p class="text-sm uppercase tracking-[0.2em] text-slate-300">Total Shopping Cost</p>
            <p class="mt-2 text-3xl font-semibold">${{ formatAmount(totalCost) }}</p>
          </div>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import api from '../api'

const shoppingItems = ref([])
const form = ref({
  name: '',
  category: '',
  price: null,
  date: '',
})

const loadShoppingItems = async () => {
  try {
    const response = await api.get('/api/shopping')
    shoppingItems.value = response.data || []
  } catch (error) {
    console.error('Failed to load shopping items', error)
  }
}

const submitShopping = async () => {
  try {
    const payload = {
      name: form.value.name,
      category: form.value.category,
      price: form.value.price,
      date: form.value.date,
    }
    await api.post('/api/shopping', payload)
    await loadShoppingItems()
    form.value.name = ''
    form.value.category = ''
    form.value.price = null
    form.value.date = ''
  } catch (error) {
    console.error('Failed to submit shopping item', error)
  }
}

const totalCost = computed(() => {
  return shoppingItems.value.reduce((sum, item) => sum + Number(item.price || 0), 0)
})

const formatAmount = (value) => {
  const amount = Number(value || 0)
  return amount.toFixed(2)
}

const formatDate = (value) => {
  if (!value) return ''
  const date = new Date(value)
  return date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

onMounted(loadShoppingItems)
</script>
